BEGIN work;

ALTER TABLE DnD.Debiti
    ADD FOREIGN KEY (Debitore) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Creditore) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Adesione
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Evento,Data) REFERENCES DnD.Eventi(Nome,Data) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Attunement
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Oggetto) REFERENCES DnD.Oggetti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Presenza
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Luogo) REFERENCES DnD.Luoghi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Origine_P_R
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Razza) REFERENCES DnD.Razze(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Studiare
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Incantesimo) REFERENCES DnD.Incantesimi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Inventario
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Oggetto) REFERENCES DnD.Oggetti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Passato
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Background) REFERENCES DnD.Background(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Affiliazione
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Gruppo,DataFondazione) REFERENCES DnD.Gruppi(Nome,DataFondazione) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Dove
    ADD FOREIGN KEY (Luogo) REFERENCES DnD.Luoghi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Evento,Data) REFERENCES DnD.Eventi(Nome,Data) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Effetto
    ADD FOREIGN KEY (Evento,Data) REFERENCES DnD.Eventi(Nome,Data) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Oggetto) REFERENCES DnD.Oggetti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Avvenimento
    ADD FOREIGN KEY (Evento,Data) REFERENCES DnD.Eventi(Nome,Data) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Sessione) REFERENCES DnD.Sessioni(Numero) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Quando
    ADD FOREIGN KEY (Evento,Data) REFERENCES DnD.Eventi(Nome,Data) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (ArcoNarrativo) REFERENCES DnD.ArchiNarrativi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.FarParte
    ADD FOREIGN KEY (Evento,Data) REFERENCES DnD.Eventi(Nome,Data) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Gruppo,DataFondazione) REFERENCES DnD.Gruppi(Nome,DataFondazione) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Giocare
    ADD FOREIGN KEY (Giocatore) REFERENCES DnD.Giocatori(CodiceFiscale) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Sessione) REFERENCES DnD.Sessioni(Numero) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Episodi
    ADD FOREIGN KEY (ArcoNarrativo) REFERENCES DnD.ArchiNarrativi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Sessione) REFERENCES DnD.Sessioni(Numero) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Riguardare
    ADD FOREIGN KEY (Gruppo,DataFondazione) REFERENCES DnD.Gruppi(Nome,DataFondazione) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Sessione) REFERENCES DnD.Sessioni(Numero) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Visita 
    ADD FOREIGN KEY (Sessione) REFERENCES DnD.Sessioni(Numero) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Luogo) REFERENCES DnD.Luoghi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Posizione
    ADD FOREIGN KEY (Oggetto) REFERENCES DnD.Oggetti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Luogo) REFERENCES DnD.Luoghi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Dono 
    ADD FOREIGN KEY (Oggetto) REFERENCES DnD.Oggetti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Abilita) REFERENCES DnD.Abilita(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Sviluppo
    ADD FOREIGN KEY (Classe) REFERENCES DnD.Classi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Abilita) REFERENCES DnD.Abilita(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Area 
    ADD FOREIGN KEY (Esterno) REFERENCES DnD.Luoghi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Interno) REFERENCES DnD.Luoghi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Componenti
    ADD FOREIGN KEY (Incantesimo) REFERENCES DnD.Incantesimi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Oggetto) REFERENCES DnD.Oggetti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Conoscenza
    ADD FOREIGN KEY (incantesimo) REFERENCES DnD.incantesimi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Classe) REFERENCES DnD.Classi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Conferire
    ADD FOREIGN KEY (Background) REFERENCES DnD.Background(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Abilita) REFERENCES DnD.Abilita(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Equipaggiamento
    ADD FOREIGN KEY (Background) REFERENCES DnD.Background(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Oggetto) REFERENCES DnD.oggetti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Origine_F_B 
    ADD FOREIGN KEY (Background) REFERENCES DnD.Background(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Fonte) REFERENCES DnD.Fonti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Origine_F_I
    ADD FOREIGN KEY (Incantesimo) REFERENCES DnD.incantesimi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Fonte) REFERENCES DnD.Fonti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Origine_F_OM
    ADD FOREIGN KEY (Oggetto) REFERENCES DnD.Oggetti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Fonte) REFERENCES DnD.Fonti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Origine_F_C
    ADD FOREIGN KEY (Classe) REFERENCES DnD.Classi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Fonte) REFERENCES DnD.Fonti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Origine_F_R 
    ADD FOREIGN KEY (Razza) REFERENCES DnD.Razze(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Fonte) REFERENCES DnD.Fonti(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Innato
    ADD FOREIGN KEY (Razza) REFERENCES DnD.Razze(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Abilita) REFERENCES DnD.Abilita(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Progressione
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Classe) REFERENCES DnD.Classi(Nome) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DnD.Controllo
    ADD FOREIGN KEY (Personaggio) REFERENCES DnD.Personaggi(id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD FOREIGN KEY (Giocatore) REFERENCES DnD.Giocatori(CodiceFiscale) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;


COMMIT work;